apiVersion: v2
name: polkadot-basic-notification
description: A Helm chart for Kubernetes
type: application
version: 1.0.3
appVersion: "0.1.0"
maintainers:
  - name: Parity
    url: https://github.com/paritytech/helm-charts
    email: devops+helm@parity.io
