{{- if .Values.node.serviceMonitor.enabled }}
{{ $fullname :=  include "chart.fullname" . }}
{{ $serviceLabels :=  include "chart.serviceLabels" .  }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $fullname }}
  {{- if $.Values.node.serviceMonitor.namespace }}
  namespace: {{ $.Values.node.serviceMonitor.namespace }}
  {{- else }}
  namespace: {{ $.Release.Namespace }}
  {{- end }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- $serviceLabels | nindent 6 }}
  endpoints:
    - port: prometheus
      path: /metrics
      {{- if $.Values.node.serviceMonitor.interval }}
      interval: {{ $.Values.node.serviceMonitor.interval }}
      {{- end }}
      {{- if $.Values.node.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ $.Values.node.serviceMonitor.scrapeTimeout }}
  {{- end }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  targetLabels:
    - chain
    - instance
{{- end }}
