apiVersion: v2
name: staking-miner
description: A Helm chart to deploy staking miner (https://github.com/paritytech/staking-miner)
type: application
version: 2.0.0
maintainers:
  - name: Parity
    url: https://github.com/paritytech/helm-charts
    email: devops+helm@parity.io
dependencies:
- name: common
  version: 1.14.1
  repository: https://charts.bitnami.com/bitnami
