apiVersion: v2
name: substrate-faucet
description: A Helm chart to deploy substrate-faucet
type: application
version: 3.0.2
maintainers:
  - name: Parity
    url: https://github.com/paritytech/helm-charts
    email: devops+helm@parity.io
dependencies:
  - name: postgresql
    version: "12.8.3"
    repository: "https://charts.bitnami.com/bitnami"
