apiVersion: v2
name: substrate-faucet
description: A Helm chart to deploy substrate-faucet
type: application
version: 1.1.0
maintainers:
  - name: Parity
    url: https://github.com/paritytech/helm-charts
