apiVersion: v2
name: polkadot-introspector
description: A Helm chart to deploy polkadot-introspector
type: application
version: 0.4.5
appVersion: "1.0.0"
maintainers:
  - name: Parity
    url: https://github.com/paritytech/helm-charts
    email: devops+helm@parity.io
