apiVersion: v2
name: testnet-manager
description: A Helm chart to deploy testnet-manager
type: application
version: 1.3.1
appVersion: "1.0.0"
maintainers:
  - name: Parity
    url: https://github.com/paritytech/helm-charts
    email: devops+helm@parity.io
