apiVersion: v2
name: node
description: A Helm chart to deploy Substrate/Polkadot nodes
type: application
version: 3.3.0
maintainers:
  - name: Parity
    url: https://github.com/paritytech/helm-charts
